// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VeriFinans.Data;

#nullable disable

namespace VeriFinans.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260512003456_UpdateUserCategoryRelationship")]
    partial class UpdateUserCategoryRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VeriFinans.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = 1,
                            Name = "Gençler Apt.",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Level = 1,
                            Name = "Tekirdağ",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Level = 1,
                            Name = "Özberk Apt.",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Level = 1,
                            Name = "Market",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Level = 1,
                            Name = "Kasap",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Level = 1,
                            Name = "Sigorta",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Level = 1,
                            Name = "Vergi",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Level = 1,
                            Name = "Eczane",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Level = 1,
                            Name = "Kediler",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Level = 1,
                            Name = "Telefonlar",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Level = 1,
                            Name = "Araba",
                            Type = 1
                        },
                        new
                        {
                            Id = 100,
                            Level = 1,
                            Name = "Maaş",
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            Level = 2,
                            Name = "Gençler",
                            ParentId = 6,
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            Level = 2,
                            Name = "Yazlık",
                            ParentId = 6,
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            Level = 2,
                            Name = "Özberk",
                            ParentId = 6,
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            Level = 2,
                            Name = "Sercan",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            Level = 2,
                            Name = "Hakkı",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            Level = 2,
                            Name = "Ayşem",
                            ParentId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 18,
                            Level = 2,
                            Name = "FR 2104",
                            ParentId = 11,
                            Type = 1
                        },
                        new
                        {
                            Id = 19,
                            Level = 2,
                            Name = "KC 105",
                            ParentId = 11,
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            Level = 2,
                            Name = "Aidat",
                            ParentId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            Level = 2,
                            Name = "Doğalgaz",
                            ParentId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 22,
                            Level = 2,
                            Name = "Elektrik",
                            ParentId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            Level = 2,
                            Name = "Su",
                            ParentId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 24,
                            Level = 2,
                            Name = "İnternet",
                            ParentId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 25,
                            Level = 2,
                            Name = "Aidat",
                            ParentId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 26,
                            Level = 2,
                            Name = "Doğalgaz",
                            ParentId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 33,
                            Level = 2,
                            Name = "Elektrik",
                            ParentId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 34,
                            Level = 2,
                            Name = "Su",
                            ParentId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 35,
                            Level = 2,
                            Name = "İnternet",
                            ParentId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 36,
                            Level = 2,
                            Name = "Aidat",
                            ParentId = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 37,
                            Level = 2,
                            Name = "Doğalgaz",
                            ParentId = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 38,
                            Level = 2,
                            Name = "Elektrik",
                            ParentId = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 39,
                            Level = 2,
                            Name = "Su",
                            ParentId = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 40,
                            Level = 2,
                            Name = "İnternet",
                            ParentId = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 27,
                            Level = 3,
                            Name = "DASK",
                            ParentId = 12,
                            Type = 1
                        },
                        new
                        {
                            Id = 28,
                            Level = 3,
                            Name = "Yangın",
                            ParentId = 12,
                            Type = 1
                        },
                        new
                        {
                            Id = 29,
                            Level = 3,
                            Name = "Kasko",
                            ParentId = 18,
                            Type = 1
                        },
                        new
                        {
                            Id = 30,
                            Level = 3,
                            Name = "Trafik Sigortası",
                            ParentId = 18,
                            Type = 1
                        },
                        new
                        {
                            Id = 31,
                            Level = 3,
                            Name = "MTV",
                            ParentId = 18,
                            Type = 1
                        },
                        new
                        {
                            Id = 32,
                            Level = 3,
                            Name = "Benzin",
                            ParentId = 18,
                            Type = 1
                        },
                        new
                        {
                            Id = 41,
                            Level = 3,
                            Name = "Kasko",
                            ParentId = 19,
                            Type = 1
                        },
                        new
                        {
                            Id = 42,
                            Level = 3,
                            Name = "Trafik Sigortası",
                            ParentId = 19,
                            Type = 1
                        },
                        new
                        {
                            Id = 43,
                            Level = 3,
                            Name = "MTV",
                            ParentId = 19,
                            Type = 1
                        },
                        new
                        {
                            Id = 44,
                            Level = 3,
                            Name = "Benzin",
                            ParentId = 19,
                            Type = 1
                        });
                });

            modelBuilder.Entity("VeriFinans.Models.CreditCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ClosingDay")
                        .HasColumnType("integer");

                    b.Property<decimal>("CurrentDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Limit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("VeriFinans.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreditCardId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentInstallment")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("InstallmentCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<int>("RecurringDay")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreditCardId");

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("VeriFinans.Models.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("VeriFinans.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("VeriFinans.Models.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoIncomeEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IncomeDayOfMonth")
                        .HasColumnType("integer");

                    b.Property<decimal>("MonthlyIncomeAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("VeriFinans.Models.Category", b =>
                {
                    b.HasOne("VeriFinans.Models.Category", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeriFinans.Models.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeriFinans.Models.CreditCard", b =>
                {
                    b.HasOne("VeriFinans.Models.User", "User")
                        .WithMany("CreditCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeriFinans.Models.Expense", b =>
                {
                    b.HasOne("VeriFinans.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeriFinans.Models.CreditCard", "CreditCard")
                        .WithMany("Expenses")
                        .HasForeignKey("CreditCardId");

                    b.HasOne("VeriFinans.Models.User", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CreditCard");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeriFinans.Models.Income", b =>
                {
                    b.HasOne("VeriFinans.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeriFinans.Models.User", "User")
                        .WithMany("Incomes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeriFinans.Models.Wallet", b =>
                {
                    b.HasOne("VeriFinans.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeriFinans.Models.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("VeriFinans.Models.CreditCard", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("VeriFinans.Models.User", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("CreditCards");

                    b.Navigation("Expenses");

                    b.Navigation("Incomes");
                });
#pragma warning restore 612, 618
        }
    }
}
